// <auto-generated />

using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StoreFlow.Inventarios.API.Datos;

#nullable disable

namespace StoreFlow.Inventarios.API.Migrations
{
    [DbContext(typeof(InventariosDbContext))]
    [Migration("20250517175114_AgregarBodegaEInventarioPorBodega")]
    partial class AgregarBodegaEInventarioPorBodega
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StoreFlow.Inventarios.API.Entidades.Bodega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Bodegas", (string)null);
                });

            modelBuilder.Entity("StoreFlow.Inventarios.API.Entidades.Inventario", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("integer");

                    b.Property<int>("IdBodega")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.HasKey("IdProducto", "IdBodega");

                    b.HasIndex("IdBodega");

                    b.ToTable("Inventarios", (string)null);
                });

            modelBuilder.Entity("StoreFlow.Inventarios.API.Entidades.Inventario", b =>
                {
                    b.HasOne("StoreFlow.Inventarios.API.Entidades.Bodega", "Bodega")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdBodega")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bodega");
                });

            modelBuilder.Entity("StoreFlow.Inventarios.API.Entidades.Bodega", b =>
                {
                    b.Navigation("Inventarios");
                });
#pragma warning restore 612, 618
        }
    }
}
