// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StoreFlow.Inventarios.API.Datos;

#nullable disable

namespace StoreFlow.Inventarios.API.Migrations
{
    [DbContext(typeof(InventariosDbContext))]
    [Migration("20250428010608_DatosSemillaInventarioInicial")]
    partial class DatosSemillaInventarioInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StoreFlow.Inventarios.API.Entidades.Inventario", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.HasKey("IdProducto");

                    b.ToTable("Inventarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
