apiVersion: apps/v1
kind: Deployment
metadata:
  name: orquestador
  namespace: storeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orquestador
  template:
    metadata:
      labels:
        app: orquestador
    spec:
      containers:
        - name: orquestador
          image: ghcr.io/miso-proyecto-final-grupo-20/proyectointegrador2/orquestador
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_HOST
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_URL
            - name: OTEL_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OTEL_ENDPOINT