services:
  dbusuarios:
    image: postgres:15
    container_name: dbusuarios
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usuarios
    ports:
        - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  usuarios:
    build: 
      context: StoreFlow.Usuarios
      dockerfile: StoreFlow.Usuarios.API/Dockerfile 
    env_file:
      - .env
    ports:
      - '8090:8080' 
    depends_on:
      dbusuarios:
        condition: service_healthy

  dbcompras:
    image: postgres
    container_name: dbcompras
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: compras
    ports:
        - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  compras:
    build: 
      context: Backend/StoreFlow.Compras
      dockerfile: StoreFlow.Compras.API/Dockerfile 
    env_file:
      - .env
    ports:
      - '8091:8080' 
    depends_on:
      dbcompras:
        condition: service_healthy      
    
  mobileapp:
    build:
      context: ./UI
      dockerfile: apps/mobile/Dockerfile
    ports:
      - '8100:80'
    depends_on:
      - 'usuarios'
