apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: storeflow
type: Opaque
stringData:
  CONNECTION_STRING: Host=dbusuarios;Port=5432;Username=postgres;Password=postgres;Database=usuarios
  CONNECTION_STRING_COMPRAS: Host=dbcompras;Port=5432;Username=postgres;Password=postgres;Database=dbcompras
  CONNECTION_STRING_VENTAS: Host=dbventas;Port=5433;Username=postgres;Password=postgres;Database=dbventas
  JWT_SECRET: q9zM3u9Y5xUq4OEt5nq3P9+0uOaIxQeH+dE68Z8+WBA=