apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: storeflow
type: Opaque
stringData:
  CONNECTION_STRING: Host=dbusuarios;Port=5432;Username=postgres;Password=postgres;Database=usuarios
  CONNECTION_STRING_COMPRAS: Host=dbcompras;Port=5432;Username=postgres;Password=postgres;Database=compras
  CONNECTION_STRING_VENTAS: Host=dbventas;Port=5432;Username=postgres;Password=postgres;Database=ventas
  CONNECTION_STRING_INVENTARIOS: Host=dbinventarios;Port=5432;Username=postgres;Password=postgres;Database=inventarios
  CONNECTION_STRING_LOGISTICA: Host=dblogistica;Port=5432;Username=postgres;Password=postgres;Database=logistica
  JWT_SECRET: q9zM3u9Y5xUq4OEt5nq3P9+0uOaIxQeH+dE68Z8+WBA=
  RABBITMQ_HOST: amqp://guest:guest@rabbitmq-internal:5672
  OTEL_ENDPOINT: http://aspire-dashboard-internal:18889
  REDIS_URL: redis-stack-internal:6379
  AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=https;AccountName=pocstoreflow;AccountKey=xxxx;EndpointSuffix=core.windows.net
  AZURE_OPENAI_ENDPOINT: https://storeflow-openai.openai.azure.com/
  AZURE_OPENAI_KEY: xxx
  AZURE_OPENAI_DEPLOYMENT: storeflow-gpt4o
