// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StoreFlow.Ventas.API.Datos;

#nullable disable

namespace StoreFlow.Ventas.API.Migrations
{
    [ExcludeFromCodeCoverage]
    [DbContext(typeof(VentasDbContext))]
    partial class VentasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StoreFlow.Ventas.API.Entidades.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DireccionEntrega")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<int?>("IdVendedor")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreVendedor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("StoreFlow.Ventas.API.Entidades.PeriodoTiempo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("PeriodosTiempo", (string)null);
                });

            modelBuilder.Entity("StoreFlow.Ventas.API.Entidades.PlanVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PeriodoTiempoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodoTiempoId");

                    b.ToTable("PlanesVenta", (string)null);
                });

            modelBuilder.Entity("StoreFlow.Ventas.API.Entidades.ProductoPedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .HasColumnType("integer");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Imagen")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<bool>("TieneInventario")
                        .HasColumnType("boolean");

                    b.HasKey("IdPedido", "IdProducto");

                    b.ToTable("ProductosPedidos", (string)null);
                });

            modelBuilder.Entity("StoreFlow.Ventas.API.Entidades.PlanVenta", b =>
                {
                    b.HasOne("StoreFlow.Ventas.API.Entidades.PeriodoTiempo", "PeriodoTiempo")
                        .WithMany("PlanesVenta")
                        .HasForeignKey("PeriodoTiempoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodoTiempo");
                });

            modelBuilder.Entity("StoreFlow.Ventas.API.Entidades.ProductoPedido", b =>
                {
                    b.HasOne("StoreFlow.Ventas.API.Entidades.Pedido", null)
                        .WithMany("ProductosPedidos")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StoreFlow.Ventas.API.Entidades.Pedido", b =>
                {
                    b.Navigation("ProductosPedidos");
                });

            modelBuilder.Entity("StoreFlow.Ventas.API.Entidades.PeriodoTiempo", b =>
                {
                    b.Navigation("PlanesVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
