apiVersion: v1
kind: Service
metadata:
  name: dblogistica-publico
  namespace: storeflow
  labels:
    app: dblogistica
    entorno: pruebas
spec:
  type: LoadBalancer
  selector:
    app: dblogistica
  ports:
    - port: 5432
      targetPort: 5432