apiVersion: v1
kind: Service
metadata:
  name: redis-stack-public
  namespace: storeflow
spec:
  type: LoadBalancer
  selector:
    app: redis-stack
  ports:
    - port: 8001
      targetPort: 8001
      name: webui