apiVersion: v1
kind: Service
metadata:
  name: redis-stack-internal
  namespace: storeflow
spec:
  type: ClusterIP
  selector:
    app: redis-stack
  ports:
    - port: 6379
      targetPort: 6379
      name: redis