apiVersion: v1
kind: Service
metadata:
  name: dbusuarios-publico
  namespace: storeflow
  labels:
    app: dbusuarios
    entorno: pruebas
spec:
  type: LoadBalancer
  selector:
    app: dbusuarios
  ports:
    - port: 5432
      targetPort: 5432
