apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistica
  namespace: storeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logistica
  template:
    metadata:
      labels:
        app: logistica
    spec:
      containers:
        - name: logistica
          image: ghcr.io/miso-proyecto-final-grupo-20/proyectointegrador2/logistica
          ports:
            - containerPort: 8080
          env:
            - name: CONNECTION_STRING_LOGISTICA
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CONNECTION_STRING_LOGISTICA
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_HOST
            - name: OTEL_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OTEL_ENDPOINT