apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios
  namespace: storeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
        - name: usuarios
          image: ghcr.io/miso-proyecto-final-grupo-20/proyectointegrador2/usuarios
          ports:
            - containerPort: 8080
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CONNECTION_STRING
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_HOST
            - name: OTEL_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OTEL_ENDPOINT
