apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios
  namespace: storeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
        - name: usuarios
          image: fcamilob/usuariospr2:v1
          ports:
            - containerPort: 8080
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CONNECTION_STRING
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
