apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbcompras
  namespace: storeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbcompras
  template:
    metadata:
      labels:
        app: dbcompras
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: compras
            - name: PGDATA
              value: /data/db
          volumeMounts:
            - name: postgres-compras-storage
              mountPath: /data
      volumes:
        - name: postgres-compras-storage
          persistentVolumeClaim:
            claimName: postgres-compras-pvc
