apiVersion: v1
kind: Service
metadata:
  name: dbcompras-publico
  namespace: storeflow
  labels:
    app: dbcompras
    entorno: pruebas
spec:
  type: LoadBalancer
  selector:
    app: dbcompras
  ports:
    - port: 5432
      targetPort: 5432
