apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-public
  namespace: storeflow
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - port: 15672
      targetPort: 15672
      name: management