apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-internal
  namespace: storeflow
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp