name: "Build, Push & Deploy to AKS - StoreFlow"

on:
  workflow_dispatch:
    inputs:
      build_all:
        description: 'Build regardless of changes'
        type: boolean
        required: false
        default: false
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository_owner }}/${{ github.event.repository.name }}
  AKS_RESOURCE_GROUP: terraform-aks-dev
  AKS_CLUSTER_NAME: terraform-aks-dev-cluster

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      should_build_all: ${{ steps.set-build-all.outputs.should_build_all }}
      usuarios-service: ${{ steps.set-build-all.outputs.should_build_all == 'true' || steps.filter.outputs.usuarios-service }}
    steps:
      - name: Set build all flag
        id: set-build-all
        shell: bash
        run: |
          BUILD_ALL="${{ github.event.inputs.build_all }}"
          if [ "$BUILD_ALL" = "true" ]; then
            echo "should_build_all=true" >> "$GITHUB_OUTPUT"
          else
            echo "should_build_all=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            usuarios-service:
              - 'StoreFlow.Usuarios/StoreFlow.Usuarios.API/**'
              - 'StoreFlow.Usuarios/StoreFlow.Usuarios.API/Dockerfile'
              - 'docker-compose.yaml'

  build-and-push:
    needs: detect-changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase image prefix and version
        run: |
          echo "LOWERCASE_PREFIX=$(echo ${{ env.IMAGE_PREFIX }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "VERSION=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_ENV

      - name: Build and push Usuarios Service
        if: needs.detect-changes.outputs.usuarios-service == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./StoreFlow.Usuarios/StoreFlow.Usuarios.API
          file: ./StoreFlow.Usuarios/StoreFlow.Usuarios.API/Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          tags: |
            ${{ env.REGISTRY }}/${{ env.LOWERCASE_PREFIX }}/usuarios:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.LOWERCASE_PREFIX }}/usuarios:latest

  deploy-to-aks:
    needs: [detect-changes, build-and-push]
    runs-on: ubuntu-latest
    if: needs.detect-changes.outputs.usuarios-service == 'true'
    steps:
      - name: Set lowercase image prefix
        run: echo "LOWERCASE_PREFIX=$(echo ${{ env.IMAGE_PREFIX }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Check if AKS cluster exists
        id: aks-check
        run: |
          if az aks show --name ${{ env.AKS_CLUSTER_NAME }} --resource-group ${{ env.AKS_RESOURCE_GROUP }} &> /dev/null; then
            echo "AKS_EXISTS=true" >> $GITHUB_ENV
          else
            echo "AKS_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Get AKS credentials
        if: env.AKS_EXISTS == 'true'
        run: |
          az aks get-credentials --resource-group ${{ env.AKS_RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }} --admin --overwrite-existing

      - name: Update usuarios image in AKS
        if: env.AKS_EXISTS == 'true' && needs.detect-changes.outputs.usuarios-service == 'true'
        run: |
          kubectl set image deployment/usuarios usuarios=${{ env.REGISTRY }}/${{ env.LOWERCASE_PREFIX }}/usuarios:${{ env.VERSION }} -n storeflow

  cleanup:
    needs: [detect-changes, build-and-push]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set lowercase repository name
        run: |
          echo "REPO_NAME=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Delete old Usuarios images
        if: needs.detect-changes.outputs.usuarios-service == 'true'
        continue-on-error: true
        uses: actions/delete-package-versions@v4
        with:
          package-name: '${{ env.REPO_NAME }}/usuarios'
          package-type: 'container'
          min-versions-to-keep: 3
          delete-only-untagged-versions: false
          token: ${{ secrets.GITHUB_TOKEN }}