name: UI CI Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'UI/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'UI/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      CI: true

    strategy:
      matrix:
        app: [web, mobile] # Define the apps to build and test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Cache Nx workspace
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: ${{ runner.os }}-nx-${{ hashFiles('**/project.json', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nx-

      - name: Build ${{ matrix.app }} app
        run: npx nx build ${{ matrix.app }} --configuration=production

      - name: Run tests for ${{ matrix.app }} app
        run: npx nx test ${{ matrix.app }} --no-watch --no-progress

      - name: Upload test results for ${{ matrix.app }} app
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.app }}-test-results
          path: 'dist/test-results/${{ matrix.app }}/**/*.xml'
          if-no-files-found: warn

      - name: Archive build for ${{ matrix.app }} app
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.app }}-build
          path: dist/apps/${{ matrix.app }}/
          retention-days: 7